---
dependencies:
  - role: Datadog.datadog
    datadog_api_key: "{{datadog.api_key}}"
    datadog_agent_version: '1:6.3.0-1'

    datadog_config:
      tags:
        - app:horizon
        - env:prod
        - stellar-network:{{horizon.network.name}}
      collect_ec2_tags: true
      use_dogstatsd: no
      logs_enabled: true

    datadog_checks:

      ntp:
        init_config:
        instances:
          - offset_threshold: 60
            host: 169.254.169.123  # amazon ntp

      docker:
        logs:
          - type: docker
            image: kinecosystem/horizon
            service: horizon
            source: go

          - type: docker
            image: kinecosystem/horizon-nginx-proxy
            service: horizon-nginx-proxy
            source: nginx

      nginx:
        init_config:
        instances:
          - nginx_status_url: http://localhost:80/nginx_status/

      http_check:
        instances:
          - name: horizon-health-check
            url: http://localhost:8001/status
            timeout: 5

            http_response_status_code: 200

      json_check:
        init_config:
          default_timeout: 5

        instances:
          - url: http://localhost:80/metrics
            metrics:
              # Metrics that include "count" report the 5 minute moving avg per second of this metric

              - horizon.goroutines: goroutines.value                                    # goroutines used by the horizon app

              - horizon.elder_ledger: '"history.elder_ledger".value'                    # oldest ledger in the horizon db
              - horizon.latest_ledger: '"history.latest_ledger".value'                  # newest ledger in the horizon db

              - horizon.open_connections: '"history.open_connections".value'            # open connections to the horizon database
              - horizon.core_open_connections: '"stellar_core.open_connections".value'  # open connections to the stellar core database

              - horizon.requests_failed: '"requests.failed"."count"'                    # failed requests to horizon (400<= status code < 600)
              - horizon.requests_succeeded: '"requests.succeeded"."count"'              # successful requests to horizon (200<= status code < 400)
              - horizon.requests_total: '"requests.total"."count"'                      # total requests to this horizon

              - horizon.txsub_buffered: '"txsub.buffered".value'                        # submission buffered in the submission queue
              - horizon.txsub_open: '"txsub.open".value'                                # transactions that have yet to be confirmed as successful or failed
              - horizon.txsub_succeeded: '"txsub.succeeded"."count"'                    # successfull transactions sent from this horizon
              - horizon.txsub_failed: '"txsub.failed"."count"'                          # failed transactions sent from this proccess
              - horizon.txsub_total: '"txsub.total"."count"'                            # total number of transactions sent to this horizon

              - horizon.requests_failed_5m_rate: '"requests.failed"."5m.rate"'
              - horizon.requests_succeeded_5m_rate: '"requests.succeeded"."5m.rate"'
              - horizon.requests_total_5m_rate: '"requests.total"."5m.rate"'

              - horizon.txsub_failed_5m_rate: '"txsub.failed"."5m.rate"'
              - horizon.txsub_succeeded_5m_rate: '"txsub.succeeded"."5m.rate"'
              - horizon.txsub_total_5m_rate: '"txsub.total"."5m.rate"'

  - role: datadog-json-check
