init_config:
  default_timeout: 5

instances:
#    - url:
#      metrics:
#        - metric_name: jsonpath

#History archive:
#  - url: bucketURL/.well-known/stellar-history.json
#    metrics:
#      - archive.latest_ledger: currentLedger # Latest ledger updated in the history archive

#Horizon metrics:
# - url: https://horizon.stellar.org/metrics
#   metrics:
#   # Metrics that include "5_min_rate" report the 5 minute moving avg per second of this metric
#     - horizon.goroutines: goroutines.value # goroutines used by the horizon app
#     - horizon.elder_ledger: '"history.elder_ledger".value' # oldest ledger in the horizon db
#     - horizon.latest_ledger: '"history.latest_ledger".value' # newest ledger in the horizon db
#     - horizon.open_connections: '"history.open_connections".value' # open connections to the horizon database
#     - horizon.logging_error: '"logging.error"."5_min_rate"' # error logs
#     - horizon.logging_panic: '"logging.panic"."5_min_rate"' # panic logs
#     - horizon.logging_warning: '"logging.warning"."5_min_rate"' # warning logs
#     - horizon.requests_failed: '"requests.failed"."5_min_rate"' # failed requests to horizon (400<= status code < 600)
#     - horizon.requests_succeeded: '"requests.succeeded"."5_min_rate"' # successful requests to horizon (200<= status code < 400)
#     - horizon.requests_total: '"requests.total"."5_min_rate"' # total requests to this horizon
#     - horizon.core_open_connections: '"stellar_core.latest_ledger".value' # open connections to the stellar core database
#     - horizon.txsub_buffered: '"txsub.buffered".value' # submission buffered in the submission queue
#     - horizon.txsub_failed: '"txsub.failed"."5_min_rate"' # failed transactions sent from this proccess
#     - horizon.txsub_open: '"txsub.open".value' # transactions that have yet to be confirmed as successful or failed
#     - horizon.txsub_succeeded: '"txsub.succeeded"."5_min_rate"' # successfull transactions sent from this horizon
#     - horizon.txsub_total: '"txsub.total"."5_min_rate"' # total number of transactions sent to this horizon

#Core metrics:
# - url: http://localhost:11626/metrics
#   metrics:
#   # Metrics that include "5_min_rate" report the 5 minute moving avg per second of this metric
#     # not sure what this is
#     - core.crypto_verify_hit: 'metrics."crypto.verify.hit"."5_min_rate"'
#     - core.crypto_verify_miss: 'metrics."crypto.verify.miss"."5_min_rate"'
#     - core.crypto_verify_total: 'metrics."crypto.verify.total"."5_min_rate"'

#     # herder metrics are related to implementaion of the SCP
#     - core.herder_pending-txs_age0: 'metrics."herder.pending-txs.age0".count'
#     - core.herder_pending-txs_age1: 'metrics."herder.pending-txs.age1".count'
#     - core.herder_pending-txs_age2: 'metrics."herder.pending-txs.age2".count'
#     - core.herder_pending-txs_age3: 'metrics."herder.pending-txs.age3".count'
#     - core.herder_state_changes: 'metrics."herder.state.changes"."5_min_rate"'
#     - core.herder_state_current: 'metrics."herder.state.current".count'

#     # metrics regarding the history archives
#     - core.history_catchup_failure: 'metrics."history.catchup.failure"."5_min_rate"'
#     - core.history_catchup_start: 'metrics."history.catchup.start"."5_min_rate"'
#     - core.history_catchup_success: 'metrics."history.catchup.success"."5_min_rate"'
#     - core.history_download-history-archive-state_failure: 'metrics."history.download-history-archive-state.failure"."5_min_rate"'
#     - core.history_download-history-archive-state_start: 'metrics."history.download-history-archive-state.start"."5_min_rate"'
#     - core.history_download-history-archive-state_success: 'metrics."history.download-history-archive-state.success"."5_min_rate"'
#     - core.history_publish_delay: 'metrics."history.publish.delay"."5_min_rate"'
#     - core.history_publish_failure: 'metrics."history.publish.failure"."5_min_rate"'
#     - core.history_publish_queue: 'metrics."history.publish.queue"."5_min_rate"'
#     - core.history_publish_skip: 'metrics."history.publish.skip"."5_min_rate"'
#     - core.history_publish_start: 'metrics."history.publish.start"."5_min_rate"'
#     - core.history_publish_success: 'metrics."history.publish.success"."5_min_rate"'

#     # metrics regarding ledger status
#     - core.ledger_account_add: 'metrics."ledger.account.add"."5_min_rate"'
#     - core.ledger_account_modify: 'metrics."ledger.account.modify"."5_min_rate"'
#     - core.ledger_age_closed: 'metrics."ledger.age.closed"."5_min_rate"'
#     - core.ledger_age_current-seconds: 'metrics."ledger.age.current-seconds".count'
#     - core.ledger_ledger_close: 'metrics."ledger.ledger.close"."5_min_rate"'
#     - core.ledger_memory_syncing-ledgers: 'metrics."ledger.memory.syncing-ledgers"."5_min_rate"'
#     - core.ledger_state_changes: 'metrics."ledger.state.changes"."5_min_rate"'
#     - core.ledger_state_current: 'metrics."ledger.state.current"."5_min_rate"'
#     - core.ledger_transaction_apply: 'metrics."ledger.transaction.apply"."5_min_rate"'
#     - core.ledger_trust_add: 'metrics."ledger.trust.add"."5_min_rate"'
#     - core.ledger_trust_modify: 'metrics."ledger.trust.modify"."5_min_rate"'

#     # metrics regarding peer-to-peer connections
#     - core.overlay_byte_read: 'metrics."overlay.byte.read"."5_min_rate"'
#     - core.overlay_byte_write: 'metrics."overlay.byte.write"."5_min_rate"'
#     - core.overlay_connection_attempt: 'metrics."overlay.connection.attempt"."5_min_rate"'
#     - core.overlay_connection_drop: 'metrics."overlay.connection.drop"."5_min_rate"'
#     - core.overlay_connection_establish: 'metrics."overlay.connection.establish"."5_min_rate"'
#     - core.overlay_connection_reject: 'metrics."overlay.connection.reject"."5_min_rate"'
#     - core.overlay_drop_connect-handler: 'metrics."overlay.drop.connect-handler"."5_min_rate"'
#     - core.overlay_drop_recv-auth-invalid-peer: 'metrics."overlay.drop.recv-auth-invalid-peer"."5_min_rate"'
#     - core.overlay_drop_recv-auth-reject: 'metrics."overlay.drop.recv-auth-reject"."5_min_rate"'
#     - core.overlay_drop_recv-auth-unexpected: 'metrics."overlay.drop.recv-auth-unexpected"."5_min_rate"'
#     - core.overlay_drop_recv-error: 'metrics."overlay.drop.recv-error"."5_min_rate"'
#     - core.overlay_drop_recv-hello-address: 'metrics."overlay.drop.recv-hello-address"."5_min_rate"'
#     - core.overlay_drop_recv-hello-ban: 'metrics."overlay.drop.recv-hello-ban"."5_min_rate"'
#     - core.overlay_drop_recv-hello-cert: 'metrics."overlay.drop.recv-hello-cert"."5_min_rate"'
#     - core.overlay_drop_recv-hello-net: 'metrics."overlay.drop.recv-hello-net"."5_min_rate"'
#     - core.overlay_drop_recv-hello-peerid: 'metrics."overlay.drop.recv-hello-peerid"."5_min_rate"'
#     - core.overlay_drop_recv-hello-self: 'metrics."overlay.drop.recv-hello-self"."5_min_rate"'
#     - core.overlay_drop_recv-hello-unexpected: 'metrics."overlay.drop.recv-hello-unexpected"."5_min_rate"'
#     - core.overlay_drop_recv-hello-version: 'metrics."overlay.drop.recv-hello-version"."5_min_rate"'
#     - core.overlay_drop_recv-message-decode: 'metrics."overlay.drop.recv-message-decode"."5_min_rate"'
#     - core.overlay_drop_recv-message-mac: 'metrics."overlay.drop.recv-message-mac"."5_min_rate"'
#     - core.overlay_drop_recv-message-seq: 'metrics."overlay.drop.recv-message-seq"."5_min_rate"'
#     - core.overlay_drop_recv-message-unauth: 'metrics."overlay.drop.recv-message-unauth"."5_min_rate"'
#     - core.overlay_error_read: 'metrics."overlay.error.read"."5_min_rate"'
#     - core.overlay_error_write: 'metrics."overlay.error.write"."5_min_rate"'
#     - core.overlay_item-fetcher_next-peer: 'metrics."overlay.item-fetcher.next-peer"."5_min_rate"'
#     - core.overlay_item-fetcher_reset-fetcher: 'metrics."overlay.item-fetcher.reset-fetcher"."5_min_rate"'
#     - core.overlay_memory_authenticated-peers: 'metrics."overlay.memory.authenticated-peers".count'
#     - core.overlay_memory_flood-map: 'metrics."overlay.memory.flood-map".count'
#     - core.overlay_memory_item-fetch-map: 'metrics."overlay.memory.item-fetch-map".count'
#     - core.overlay_memory_pending-peers: 'metrics."overlay.memory.pending-peers".count'
#     - core.overlay_message_broadcast: 'metrics."overlay.message.broadcast"."5_min_rate"'
#     - core.overlay_message_flood-receive: 'metrics."overlay.message.flood-receive"."5_min_rate"'
#     - core.overlay_message_read: 'metrics."overlay.message.read"."5_min_rate"'
#     - core.overlay_message_send-from-broadcast: 'metrics."overlay.message.send-from-broadcast"."5_min_rate"'
#     - core.overlay_message_write: 'metrics."overlay.message.write"."5_min_rate"'
#     - core.overlay_recv_auth: 'metrics."overlay.recv.auth"."5_min_rate"'
#     - core.overlay_recv_dont-have: 'metrics."overlay.recv.dont-have"."5_min_rate"'
#     - core.overlay_recv_error: 'metrics."overlay.recv.error"."5_min_rate"'
#     - core.overlay_recv_get-peers: 'metrics."overlay.recv.get-peers"."5_min_rate"'
#     - core.overlay_recv_get-scp-qset: 'metrics."overlay.recv.get-scp-qset"."5_min_rate"'
#     - core.overlay_recv_get-scp-state: 'metrics."overlay.recv.get-scp-state"."5_min_rate"'
#     - core.overlay_recv_get-txset: 'metrics."overlay.recv.get-txset"."5_min_rate"'
#     - core.overlay_recv_hello: 'metrics."overlay.recv.hello"."5_min_rate"'
#     - core.overlay_recv_peers: 'metrics."overlay.recv.peers"."5_min_rate"'
#     - core.overlay_recv_scp-confirm: 'metrics."overlay.recv.scp-confirm"."5_min_rate"'
#     - core.overlay_recv_scp-externalize: 'metrics."overlay.recv.scp-externalize"."5_min_rate"'
#     - core.overlay_recv_scp-message: 'metrics."overlay.recv.scp-message"."5_min_rate"'
#     - core.overlay_recv_scp-nominate: 'metrics."overlay.recv.scp-nominate"."5_min_rate"'
#     - core.overlay_recv_scp-prepare: 'metrics."overlay.recv.scp-prepare"."5_min_rate"'
#     - core.overlay_recv_scp-qset: 'metrics."overlay.recv.scp-qset"."5_min_rate"'
#     - core.overlay_recv_transaction: 'metrics."overlay.recv.transaction"."5_min_rate"'
#     - core.overlay_recv_txset: 'metrics."overlay.recv.txset"."5_min_rate"'
#     - core.overlay_send_auth: 'metrics."overlay.send.auth"."5_min_rate"'
#     - core.overlay_send_dont-have: 'metrics."overlay.send.dont-have"."5_min_rate"'
#     - core.overlay_send_error: 'metrics."overlay.send.error"."5_min_rate"'
#     - core.overlay_send_get-peers: 'metrics."overlay.send.get-peers"."5_min_rate"'
#     - core.overlay_send_get-scp-qset: 'metrics."overlay.send.get-scp-qset"."5_min_rate"'
#     - core.overlay_send_get-scp-state: 'metrics."overlay.send.get-scp-state"."5_min_rate"'
#     - core.overlay_send_get-txset: 'metrics."overlay.send.get-txset"."5_min_rate"'
#     - core.overlay_send_hello: 'metrics."overlay.send.hello"."5_min_rate"'
#     - core.overlay_send_peers: 'metrics."overlay.send.peers"."5_min_rate"'
#     - core.overlay_send_scp-message: 'metrics."overlay.send.scp-message"."5_min_rate"'
#     - core.overlay_send_scp-qset: 'metrics."overlay.send.scp-qset"."5_min_rate"'
#     - core.overlay_send_transaction: 'metrics."overlay.send.transaction"."5_min_rate"'
#     - core.overlay_send_txset: 'metrics."overlay.send.txset"."5_min_rate"'
#     - core.overlay_timeout_idle: 'metrics."overlay.timeout.idle"."5_min_rate"'

#     # number of running proccesses
#     - core.process_memory_handles: 'metrics."process.memory.handles".count'

#     # metrics regarding the SCP
#     - core.scp_ballot_accepted-commit: 'metrics."scp.ballot.accepted-commit"."5_min_rate"'
#     - core.scp_ballot_accepted-prepared: 'metrics."scp.ballot.accepted-prepared"."5_min_rate"'
#     - core.scp_ballot_confirmed-prepared: 'metrics."scp.ballot.confirmed-prepared"."5_min_rate"'
#     - core.scp_ballot_expire: 'metrics."scp.ballot.expire"."5_min_rate"'
#     - core.scp_ballot_started: 'metrics."scp.ballot.started"."5_min_rate"'
#     - core.scp_envelope_emit: 'metrics."scp.envelope.emit"."5_min_rate"'
#     - core.scp_envelope_invalidsig: 'metrics."scp.envelope.invalidsig"."5_min_rate"'
#     - core.scp_envelope_receive: 'metrics."scp.envelope.receive"."5_min_rate"'
#     - core.scp_envelope_sign: 'metrics."scp.envelope.sign"."5_min_rate"'
#     - core.scp_envelope_validsig: 'metrics."scp.envelope.validsig"."5_min_rate"'
#     - core.scp_memory_cumulative-statements: 'metrics."scp.memory.cumulative-statements".count'
#     - core.scp_memory_known-slots: 'metrics."scp.memory.known-slots".count'
#     - core.scp_memory_pending-envelopes: 'metrics."scp.memory.pending-envelopes".count'
#     - core.scp_quorum_heard: 'metrics."scp.quorum.heard"."5_min_rate"'
#     - core.scp_sync_lost: 'metrics."scp.sync.lost"."5_min_rate"'
#     - core.scp_value_candidate: 'metrics."scp.value.candidate"."5_min_rate"'
#     - core.scp_value_externalize: 'metrics."scp.value.externalize"."5_min_rate"'
#     - core.scp_value_invalid: 'metrics."scp.value.invalid"."5_min_rate"'
#     - core.scp_value_nominating: 'metrics."scp.value.nominating"."5_min_rate"'
#     - core.scp_value_valid: 'metrics."scp.value.valid"."5_min_rate"'

#     # Works are async or long activities that may fail and require retrying
#     - core.work_root_success: 'metrics."work.root.success"."5_min_rate"'
#     - core.work_unit_failure: 'metrics."work.unit.failure"."5_min_rate"'
#     - core.work_unit_run: 'metrics."work.unit.run"."5_min_rate"'
#     - core.work_unit_start: 'metrics."work.unit.start"."5_min_rate"'
#     - core.work_unit_success: 'metrics."work.unit.success"."5_min_rate"'

