---
version: "3"

services:
  horizon-nginx-proxy:
    image: kinecosystem/horizon-nginx-proxy:c2bf889
    container_name: horizon-nginx-proxy

    network_mode: host

    environment:
      PROXY_LISTEN_PORT: 80
      PROXY_READ_TIMEOUT: 60
      # horizon listens on port 8000
      PROXY_PASS_URL: http://localhost:8000

    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "3"
