---
- hosts: example-stellar-core
  roles:
    - sync-clock
    - apt-get-update
    - common-packages
    - awscli
    - docker
    - add-pg_dump-96

    #- datadog-stellar-core
    - stellar-core-telegraf-client
    - stellar-core
