---
- hosts: example-stellar-core
  roles:
    - sync-clock
    - apt-get-update
    - common-packages
    - awscli
    - docker
    - add_pg_dump_96

    #- datadog-stellar-core
    - core-native-telegraf
    - stellar-core
