---
all:
  children:
    my-network:
      vars:
        ansible_become: yes
        ansible_user: ubuntu
        ansible_ssh_private_key_file: my-key.pem
        ansible_ssh_common_args: -o IdentitiesOnly=yes

      children:
        example-localhost:
          vars:
            ansible_connection: local
          hosts:
            example-local: {ansible_host: localhost}

        example-stellar-core:
          hosts:
            stellar-core-1111: {ansible_host: host1.com}
            stellar-core-2222: {ansible_host: host2.com}

        example-horizon:
          hosts:
            horizon-1111: {ansible_host: host.com}
