---
horizon:
  network:
    name: my-network
    passphrase: xxx

  nodes:
    - name: local
      s3_bucket_url: s3://something #NOTE: you'll need to manually allow the node to access this bucket. terraform doesn't do thisyet. 
      db:
        name: xxx
        user: stellar
        password: xxx
        host: xxx
      stellar_core:
        url: xxx
        db:
          name: xxx
          user: stellar
          password: xxx
          host: xxx
