---
horizon:
  network:
    name: my-network
    passphrase: xxx

  nodes:
    - name: local
      aws_region: us-east-1
      s3_bucket_url: s3://something
      db:
        name: xxx
        user: stellar
        password: xxx
        host: xxx
      stellar_core:
        url: xxx
        db:
          name: xxx
          user: stellar
          password: xxx
          host: xxx
          cursor_name: 'HORIZON'
