version: "3"

services:
  health_check:
    image: kinecosystem/horizon_health_check:c8407ce
    ports:
      - 8000:8000
    environment:
      BUILD_VERSION: c8407ce
      REQUEST_TIMEOUT: 2
      CORE_INFO_URL: http://xxxxx:11626/info
