version: "3"

services:
  stellar-core:
    image: kinfoundation/stellar-core
    build:
      dockerfile: Dockerfile.stellar-core
      context: .
    ports:
      - 11625:11625
      - 11626:11626
    links:
      - stellar-core-db
    volumes:
      - ./stellar-core/opt/stellar-core:/opt/stellar-core
      - ./stellar-core/tmp/stlelar-core:/tmp/stellar-core

  stellar-core-db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=stellar
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=core
    ports:
      - 5432:5432

  horizon:
    image: kinfoundation/horizon
    build:
      dockerfile: Dockerfile.horizon
      context: .
    ports:
      - 8000:8000
    links: 
      - horizon-db
      - stellar-core
      - stellar-core-db
    volumes:
      - ./horizon/opt/horizon/opt/horizon
    environment:
      - DATABASE_URL="postgres://stellar:12345678@horizon-db/horizon?sslmode=disable"
      - STELLAR_CORE_DATABASE_URL="postgres://stellar:12345678@stellar-core-db/core?sslmode=disable"
      - STELLAR_CORE_URL="http://stellar-core:11626"
      - LOG_LEVEL="info"
      - INGEST="true"
      - PER_HOUR_RATE_LIMIT="999999"
      - NETWORK_PASSPHRASE="private testnet"

  horizon-db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=stellar
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=horizon
    ports:
      - 5433:5432
