version: "3"

services:
  stellar-core:
    image: kinfoundation/stellar-core
    build:
      dockerfile: Dockerfile.stellar-core
      context: .
    ports:
      - 11625:11625
      - 11626:11626
    links:
      - stellar-core-db
    volumes:
      - ./stellar-core/opt/stellar-core:/opt/stellar-core
      - ./stellar-core/tmp/stlelar-core:/tmp/stellar-core
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "3"

  stellar-core-db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=stellar
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=core
    ports:
      - 5432:5432

  horizon:
    image: kinfoundation/horizon
    build:
      dockerfile: Dockerfile.horizon
      context: .
    ports:
      - 8000:8000
    links: 
      - horizon-db
      - stellar-core
      - stellar-core-db
    volumes:
      - ./horizon/opt/horizon:/opt/horizon
    environment:
      # available configuration visible at:
      # https://github.com/stellar/horizon/blob/v0.11.1/src/github.com/stellar/horizon/cmd/horizon/main.go#L33
      #
      DATABASE_URL: postgres://stellar:12345678@horizon-db/horizon?sslmode=disable
      STELLAR_CORE_DATABASE_URL: postgres://stellar:12345678@stellar-core-db/core?sslmode=disable
      STELLAR_CORE_URL: http://stellar-core:11626
      LOG_LEVEL: info
      INGEST: "true"
      PER_HOUR_RATE_LIMIT: "999999"
      NETWORK_PASSPHRASE: private testnet
      FRIENDBOT_SECRET: "${ROOT_ACCOUNT_SEED}"
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "3"

  horizon-db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=stellar
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=horizon
    ports:
      - 5433:5432

  # unused for now
  #
  # friendbot was originally part of horizon
  # but extracted to its own microservice since horizon v0.12.2
  # currently we're using horizon v0.11.1 which still has friendbot built-in.
  # once we upgrade, we'll have to use this as well
  friendbot:
    image: kinfoundation/friendbot
    build:
      dockerfile: Dockerfile.friendbot
      context: .
    ports:
      - 8001:8000
    links:
      - horizon
    volumes:
      - ./friendbot/opt/friendbot:/opt/friendbot
    environment:
      ROOT_ACCOUNT_SEED: "${ROOT_ACCOUNT_SEED}"
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "3"
